# =========================
# DATABASE
# =========================

spring.datasource.url=jdbc:mysql://localhost:3306/carequeue
spring.datasource.username=root
spring.datasource.password=hari@1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# =========================
# MAIL / GMAIL SMTP
# =========================

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=hariaish88893443@gmail.com
spring.mail.password=jcitlnapabejjgfd

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
