server.port=${PORT:8080}

# =========================
# DATABASE - AIVEN MYSQL
# =========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# =========================
# GMAIL SMTP
# =========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true